version: '3'

services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=wingtel
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password12345
      ports:
        - "5432:5432"
    wingtel_web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db