# Generated by Django 2.2.1 on 2020-07-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Past Due'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(db_index=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
