# Generated by Django 2.2.1 on 2020-07-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='new', max_length=10)),
                ('device_id', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('phone_model', models.CharField(default='', max_length=128)),
                ('effective_date', models.DateTimeField(null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plans.Plan')),
                ('provider_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TelecommunicationCompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
